
import React from "react";
import anggota from "../../assets/anggota.png";
import anggotabaru from "../../assets/anggotabaru.png";
import Terai from "../../assets/LogoTerai.png";
import Hubungins from "../../assets/LogoHubung'ins.png";
import Perspektif from "../../assets/LogoPerspektif.png";
import "./Halaman6.css";

function Halaman6() {
  return (
    <div
      id="connect"
      className="
    containerHal6
    text-white
    flex flex-col
    items-center
    mt-[30px]
    overflow-hidden
    md:mt-[45px]
    md:px-4
    "
    >
      <h2
        className="
        HelveticaBold
        text-[30px]
        text-white
        text-center
        md:text-[40px]
        "
      >
        Let's Connect
      </h2>
      <h2
        className="
        HelveticaBold
        text-[25px]
        text-white
        text-center
        md:text-[35px]
        "
      >
        with Us
      </h2>
      <div
        className="
        imgContainerHal6
        w-full
        mt-[20px]
        overflow-hidden
        md:h-[250px]
        md:flex
        md:justify-center
        "
      >
        <img
          src={anggotabaru}
          className="
            imgHal6
            w-[700px] 
            max-w-none
            relative
            top-[-20%] 
            left-[-40%]
            overflow-hidden
            md:static
            md:w-full
            md:max-w-[800px]
            md:top-0
            md:left-0
            "
          alt="Anggota"
        ></img>
      </div>
      <div
        className="
        containerBlob
        w-min 
        h-min
        bg-white
        top-[280px]
        left-[10px]
        absolute
        flex 
        flex-nowrap
        md:top-[350px]
        "
      >
        <div
          className="
            blob
            blob1
            w-[80px] 
            h-[80px]
            bg-[#b22e15]
            blur-[20px]
            rounded-[50%]
            opacity-[0.8]
            absolute
            top-[20px]
            md:w-[100px]
            md:h-[100px]
            "
        ></div>
        <div
          className="
            blob
            blob2
            w-[80px] 
            h-[80px]
            bg-[#e0c39f]
            blur-[20px]
            rounded-[50%]
            opacity-[0.8]
            absolute
            md:w-[100px]
            md:h-[100px]
            "
        ></div>
        <div
          className="
            blob
            blob3
            w-[80px] 
            h-[80px]
            bg-[#d67e45]
            blur-[20px]
            rounded-[50%]
            opacity-[0.8]
            absolute
            top-[-20px]
            md:w-[100px]
            md:h-[100px]
            "
        ></div>
      </div>
      <div
        className="
        filterImg
        w-[400px]
        h-[80px]
        bg-black
        blur-[20px]
        z-1
        absolute
        top-[360px]
        left-[-10%]
        md:w-[2000px] 
        md:h-[200px]
        md:blur-[40px]
        md:top-[450px]
        "
      ></div>
      <div
        className="
       containerFilterImg
       w-screen
       h-fit
       "
      >
        <section
          className="
        w-screen
        flex 
        flex-row
        gap-[20px]
        items-center
        justify-center
        mt-[50px]
        z-2
        md:mt-[180px]
        md:bg-black
        md:py-4
        "
        >
          <div
            className="
            flex 
            flex-col
            items-center
            "
          >
            <h3
              className="
                HelveticaBold
                text-[15px]
                md:text-[18px]
                text-white
                "
            >
              Supported By:
            </h3>
            <div>
              <img
                src={Hubungins}
                className="
                    w-[60px]
                    md:w-[100px]
                    "
                alt="Hubungins"
              ></img>
            </div>
          </div>
          <div
            className="
            flex 
            flex-col
            items-center
            "
          >
            <h3
              className="
                HelveticaBold
                text-[15px]
                md:text-[18px]
                text-white
                "
            >
              Partner Us:
            </h3>
            <div
              className="
                flex 
                flex-row
                gap-[15px]
                md:gap-[30px]
                "
            >
              <img
                src={Terai}
                className="
                    w-[60px]
                    md:w-[100px]
                    "
                alt="Terai"
              ></img>
              <img
                src={Perspektif}
                className="
                    w-[60px]
                    md:w-[100px]
                    "
                alt="Perspektif"
              ></img>
            </div>
          </div>
        </section>
      </div>
    </div>
  );
}

export default Halaman6;
