import React from "react";
import CreativeMedia from "../../assets/CDhal3.png";
import Movement from "../../assets/Mhal3.png";
import SharingSession from "../../assets/SShal3.png";
import SocialEducation from "../../assets/SEhal3.png";
import ShortCourse from "../../assets/SChal3.png";
import "./Halaman2.css";

function Halaman2() {
  return (
    <div
      id="program"
      class="
      w-full 
      bg-[black]
      z-[1]
      flex
      flex-col
      justify-center
      items-center
      pt-32
      "
    >
      <h2
        className="
      judulHalaman2 
      text-[4rem] 
      text-[white] 
      mt-0 
      pb-16
      font-family: HelveticaBold
      sm:text-[2rem] 
      "
      >
        Our Program
      </h2>
      <section
        className="
      ContainerisiHalaman2
      flex
      flex-row 
      items-center 
      justify-center 
      flex-wrap 
      gap-[10%] 
      w-[100rem]
      sm:w-full 
      sm:gap-[6%]

      "
      >
        <div
          className="
        isiHalaman2
        text-[2rem] 
        flex 
        flex-row 
        justify-center 
        items-center 
        w-[28rem] 
        h-52 
        gap-12 
        border-[linear-gradient(#000_20%,purple,white)] 
        m-[1.5%] 
        border-[0.1rem] 
        border-solid
        sm:w-28 
        sm:flex-col-reverse 
        sm:gap-[5%]"
        >
          <img
            className="
          imgHal2
          w-32
          sm:w-24"
            src={CreativeMedia}
          ></img>
          <h3
            className="
          w-32 
          text-[2rem] 
          text-[white]
          sm:text-[1.2rem] 
          sm:pl-[16%]"
          >
            Creative Media
          </h3>
        </div>
        <div
          className="
        isiHalaman2
        text-[2rem] 
        flex 
        flex-row 
        justify-center 
        items-center 
        w-[28rem] 
        h-52 
        gap-12 
        border-[linear-gradient(#000_20%,purple,white)] 
        m-[1.5%] 
        border-[0.1rem] 
        border-solid
        sm:w-28 
        sm:flex-col-reverse 
        sm:gap-[5%]"
        >
          <img
            className="
          imgHal2
          w-32
          sm:w-24"
            src={Movement}
          ></img>
          <h3
            className="
          w-32 
          text-[2rem] 
          text-[white]
          sm:text-[1.2rem] 
          sm:pl-[16%]"
          >
            Movement
          </h3>
        </div>
        <div
          className="
        isiHalaman2
        text-[2rem] 
        flex 
        flex-row 
        justify-center 
        items-center 
        w-[28rem] 
        h-52 
        gap-12 
        border-[linear-gradient(#000_20%,purple,white)] 
        m-[1.5%] 
        border-[0.1rem] 
        border-solid
        sm:w-28 
        sm:flex-col-reverse 
        sm:gap-[5%]"
        >
          <img
            className="
          imgHal2
          w-32
          sm:w-24"
            src={SharingSession}
          ></img>
          <h3
            className="
          w-32 
          text-[2rem] 
          text-[white]
          sm:text-[1.2rem] 
          sm:pl-[16%]"
          >
            Sharing Session
          </h3>
        </div>
        <div
          className="
        isiHalaman2
        text-[2rem] 
        flex 
        flex-row 
        justify-center 
        items-center 
        w-[28rem] 
        h-52 
        gap-12 
        border-[linear-gradient(#000_20%,purple,white)] 
        m-[1.5%] 
        border-[0.1rem] 
        border-solid
        sm:w-28 
        sm:flex-col-reverse 
        sm:gap-[5%]"
        >
          <img
            className="
          imgHal2
          w-32
          sm:w-24"
            src={SocialEducation}
          ></img>
          <h3 className="
          w-32 
          text-[2rem] 
          text-[white]
          sm:text-[1.2rem] 
          sm:pl-[16%]">Social Education</h3>
        </div>
        <div
          className="
        isiHalaman2
        text-[2rem] 
        flex 
        flex-row 
        justify-center 
        items-center 
        w-[28rem] 
        h-52 
        gap-12 
        border-[linear-gradient(#000_20%,purple,white)] 
        m-[1.5%] 
        border-[0.1rem] 
        border-solid
        sm:w-28 
        sm:flex-col-reverse 
        sm:gap-[5%]"
        >
          <img
            className="
          imgHal2
          w-32
          sm:w-24"
            src={ShortCourse}
          ></img>
          <h3 className="
          w-32 
          text-[2rem] 
          text-[white]
          sm:text-[1.2rem] 
          sm:pl-[16%]">Short Course</h3>
        </div>
      </section>
    </div>
  );
}

export default Halaman2;
